export const MAX_NATIVE_TEXT_WORKER_OLD_SPACE_MB = 96;
export const MAX_NATIVE_TEXT_WORKER_YOUNG_SPACE_MB = 16;
export const MAX_OCR_RASTER_DIMENSION = 3508;
export const MAX_OCR_STDOUT_BYTES = 16 * 1024 * 1024;
export const MAX_OCR_STDERR_BYTES = 64 * 1024;
